name: aspirity_awards_table_anim
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: DIN Pro
      fonts:
        - asset: fonts/DINPro.ttf
          weight: 400
        - asset: fonts/DINPro-Medium.ttf
          weight: 500
        - asset: fonts/DINPro-Bold.ttf
          weight: 700
